=== autermann/geosoftware/src/test/resources/datasets/database.dtd
<!ELEMENT dataSet (
	OBSERVATION_CATEGORIE*,
	USER_RIGHT*,
	USER*,
	OBSERVATION*,
	SEQUENCE*)>

<!ELEMENT OBSERVATION EMPTY>
<!ATTLIST OBSERVATION
    ID CDATA #REQUIRED
    TITLE CDATA #REQUIRED
    DESCRIPTION CDATA #REQUIRED
    CREATION_TIME CDATA #REQUIRED
    OBSERVATION_CATEGORIE_ID CDATA #REQUIRED
    USER_ID CDATA #REQUIRED
    LONGITUDE CDATA #REQUIRED
    LATITUDE CDATA #REQUIRED
>

<!ELEMENT OBSERVATION_CATEGORIE EMPTY>
<!ATTLIST OBSERVATION_CATEGORIE
    ID CDATA #REQUIRED
    TITLE CDATA #REQUIRED
    DESCRIPTION CDATA #REQUIRED
>

<!ELEMENT SEQUENCE EMPTY>
<!ATTLIST SEQUENCE
    SEQ_NAME CDATA #REQUIRED
    SEQ_COUNT CDATA #IMPLIED
>

<!ELEMENT USER EMPTY>
<!ATTLIST USER
    ID CDATA #REQUIRED
    CREATION_DATE CDATA #REQUIRED
    NAME CDATA #REQUIRED
    MAIL_ADDRESS CDATA #REQUIRED
    FAMILY_NAME CDATA #REQUIRED
    HASHED_PASSWORD CDATA #REQUIRED
    USER_RIGHT_ID CDATA #REQUIRED
>

<!ELEMENT USER_RIGHT EMPTY>
<!ATTLIST USER_RIGHT
    VALUE CDATA #REQUIRED
    DESCRIPTION CDATA #REQUIRED
    NAME CDATA #REQUIRED
>

=== autermann/geosoftware/src/test/resources/datasets/database.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dataSet PUBLIC '-//Sloth//DataBase Schema 1.0//EN' 'database.dtd'>
<dataSet>
	<OBSERVATION_CATEGORIE ID="1" TITLE="Categorie 1" DESCRIPTION="Description of Categorie 1" />
	<OBSERVATION_CATEGORIE ID="2" TITLE="Categorie 1" DESCRIPTION="Description of Categorie 1" />
	<OBSERVATION_CATEGORIE ID="3" TITLE="Categorie 1" DESCRIPTION="Description of Categorie 1" />
	<USER_RIGHT VALUE="0" NAME="guest" DESCRIPTION="Description of Guests" />
	<USER_RIGHT VALUE="10" NAME="USER" DESCRIPTION="Description of Users" />
	<USER_RIGHT VALUE="20" NAME="admin" DESCRIPTION="Description of Admins" />
	<USER ID="1" MAIL_ADDRESS="USER1@exapmle.com" NAME="User" FAMILY_NAME="One" USER_RIGHT_ID="10" HASHED_PASSWORD="eins" CREATION_DATE="2010-03-07 19:10:00" />
	<USER ID="2" MAIL_ADDRESS="USER2@exapmle.com" NAME="User" FAMILY_NAME="Two" USER_RIGHT_ID="10" HASHED_PASSWORD="zwei" CREATION_DATE="2010-03-07 19:11:00" />
	<USER ID="3" MAIL_ADDRESS="USER3@exapmle.com" NAME="User" FAMILY_NAME="Three" USER_RIGHT_ID="10" HASHED_PASSWORD="drei" CREATION_DATE="2010-03-07 19:12:00" />
	<USER ID="4" MAIL_ADDRESS="USER4@exapmle.com" NAME="User" FAMILY_NAME="Four" USER_RIGHT_ID="0" HASHED_PASSWORD="vier" CREATION_DATE="2010-03-07 19:13:00" />
	<USER ID="5" MAIL_ADDRESS="USER5@exapmle.com" NAME="User" FAMILY_NAME="Five" USER_RIGHT_ID="20" HASHED_PASSWORD="fuenf" CREATION_DATE="2010-03-07 19:14:00" />
	<OBSERVATION ID="1" TITLE="Observation 1" DESCRIPTION="Description of Observation 1" USER_ID="1" CREATION_TIME="2010-03-07 19:40:00" OBSERVATION_CATEGORIE_ID="1" LONGITUDE="8.1" LATITUDE="1.8" />
	<OBSERVATION ID="2" TITLE="Observation 2" DESCRIPTION="Description of Observation 2" USER_ID="2" CREATION_TIME="2010-03-07 19:41:00" OBSERVATION_CATEGORIE_ID="2" LONGITUDE="7.2" LATITUDE="2.7" />
	<OBSERVATION ID="3" TITLE="Observation 3" DESCRIPTION="Description of Observation 3" USER_ID="3" CREATION_TIME="2010-03-07 19:42:00" OBSERVATION_CATEGORIE_ID="3" LONGITUDE="6.3" LATITUDE="3.6" />
	<OBSERVATION ID="4" TITLE="Observation 4" DESCRIPTION="Description of Observation 4" USER_ID="4" CREATION_TIME="2010-03-07 19:43:00" OBSERVATION_CATEGORIE_ID="1" LONGITUDE="5.4" LATITUDE="4.5" />
	<OBSERVATION ID="5" TITLE="Observation 5" DESCRIPTION="Description of Observation 5" USER_ID="5" CREATION_TIME="2010-03-07 19:44:00" OBSERVATION_CATEGORIE_ID="2" LONGITUDE="4.5" LATITUDE="5.4" />
	<OBSERVATION ID="6" TITLE="Observation 6" DESCRIPTION="Description of Observation 6" USER_ID="1" CREATION_TIME="2010-03-07 19:45:00" OBSERVATION_CATEGORIE_ID="3" LONGITUDE="3.6" LATITUDE="6.3" />
	<OBSERVATION ID="7" TITLE="Observation 7" DESCRIPTION="Description of Observation 7" USER_ID="2" CREATION_TIME="2010-03-07 19:46:00" OBSERVATION_CATEGORIE_ID="1" LONGITUDE="2.7" LATITUDE="7.2" />
	<OBSERVATION ID="8" TITLE="Observation 8" DESCRIPTION="Description of Observation 8" USER_ID="3" CREATION_TIME="2010-03-07 19:47:00" OBSERVATION_CATEGORIE_ID="2" LONGITUDE="1.8" LATITUDE="8.1" />
</dataSet>
